"""
scanner.py - Spectral Power Calculation & Channel Prioritization Engine
Computes FFT Power Spectral Density (PSD) across channels, calculates priority scores,
and passes high-priority channels to classifier.py for threat evaluation.
"""

import time
import numpy as np
import pandas as pd
import scipy.signal as signal

# Import machine learning classifier pipeline
try:
    from classifier import classify_channel
    HAS_CLASSIFIER = True
except ImportError:
    HAS_CLASSIFIER = False


def calculate_psd_metrics(iq_samples: np.ndarray, sample_rate: float = 1e6) -> dict:
    """
    Computes Fast Fourier Transform (FFT) based Power Spectral Density (PSD)
    and key power metrics for a complex IQ signal.
    """
    # Calculate Power Spectral Density using Welch's method
    freqs, psd = signal.welch(
        iq_samples, 
        fs=sample_rate, 
        nperseg=min(len(iq_samples), 256), 
        return_onesided=False
    )
    
    # Calculate average power in linear and decibel scales
    mean_power_linear = np.mean(np.abs(iq_samples) ** 2)
    mean_power_db = 10 * np.log10(mean_power_linear + 1e-12)
    
    # Peak power & PSD metrics
    peak_psd_linear = np.max(psd)
    peak_psd_db = 10 * np.log10(peak_psd_linear + 1e-12)
    
    return {
        "mean_power_db": float(mean_power_db),
        "peak_psd_db": float(peak_psd_db),
        "freqs": freqs,
        "psd": psd
    }


def scan_and_prioritize(
    channels_dict: dict, 
    threshold_db: float = -10.0
) -> pd.DataFrame:
    """
    Scans a batch of RF channels, calculates energy metrics, assigns dynamic priority scores,
    and classifies active channels using classifier.py.
    
    Parameters:
        channels_dict (dict): Batch dictionary generated by simulator.py
        threshold_db (float): Ambient noise floor threshold in dB
        
    Returns:
        pd.DataFrame: Table of scanned channels sorted by Priority Score (descending)
    """
    records = []
    current_time = time.strftime("%H:%M:%S")
    
    for ch_idx, ch_data in channels_dict.items():
        iq_samples = ch_data["iq"]
        sample_rate = ch_data.get("sample_rate", 1e6)
        freq_mhz = ch_data.get("freq_mhz", 100.0 + ch_idx * 15.0)
        
        # 1. FFT & Power Calculation
        psd_metrics = calculate_psd_metrics(iq_samples, sample_rate)
        power_db = psd_metrics["mean_power_db"]
        
        # 2. Priority Score Calculation
        # Base priority is determined by how far power exceeds the noise threshold
        power_excess = max(0.0, power_db - threshold_db)
        
        # 3. Threat Classification via classifier.py
        if HAS_CLASSIFIER:
            clf_result = classify_channel(iq_samples, sample_rate)
            classification = clf_result["classification"]
            threat_level = clf_result["threat_level"]
            status = clf_result["status"]
            confidence = clf_result["confidence"]
        else:
            # Fallback heuristic if classifier.py is not present
            confidence = 85.0
            if power_db < threshold_db:
                classification = "Background Noise"
                threat_level = "LOW"
                status = "CLEAR"
            elif power_db > 5.0:
                classification = "Hostile Jammer"
                threat_level = "CRITICAL"
                status = "BROADBAND JAMMING"
            elif power_db > 0.0:
                classification = "Hostile Radar"
                threat_level = "HIGH"
                status = "PULSED RADAR LOCK"
            else:
                classification = "Civilian Broadcast"
                threat_level = "LOW"
                status = "STANDARD COMM"

        # Boost priority score for high/critical threat classifications
        threat_multiplier = 1.0
        if threat_level == "CRITICAL":
            threat_multiplier = 2.5
        elif threat_level == "HIGH":
            threat_multiplier = 1.8
        elif threat_level == "MEDIUM":
            threat_multiplier = 1.2
            
        priority_score = round(power_excess * threat_multiplier, 2)
        
        records.append({
            "Channel": ch_idx,
            "Center Freq (MHz)": freq_mhz,
            "Power (dB)": round(power_db, 2),
            "Classification": classification,
            "Confidence (%)": confidence,
            "Threat Level": threat_level,
            "Status": status,
            "Priority Score": priority_score,
            "Timestamp": current_time
        })
        
    # Convert records to DataFrame and sort by Priority Score in descending order
    df = pd.DataFrame(records)
    df = df.sort_values(by="Priority Score", ascending=False).reset_index(drop=True)
    return df


if __name__ == "__main__":
    print("Testing scanner.py with synthetic batch...")
    
    # Standalone verification using simulator if available
    try:
        from simulator import generate_spectrum_batch
        test_channels = generate_spectrum_batch(num_channels=10)
    except ImportError:
        # Dummy batch generator for isolated test
        test_channels = {}
        for ch in range(5):
            test_channels[ch] = {
                "iq": (np.random.randn(1024) + 1j * np.random.randn(1024)) * (ch + 1),
                "sample_rate": 1e6,
                "freq_mhz": 100.0 + ch * 15.0
            }
            
    df_results = scan_and_prioritize(test_channels, threshold_db=-10.0)
    print("\nScan & Prioritization Results:")
    print(df_results.to_string(index=False))